version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    restart: unless-stopped
